import Head from 'next/head';
import { useRouter } from 'next/router';
import { useState } from 'react';
// hooks
import { useAuth } from '../hooks/useAuth';
import { withPublic } from '../hooks/useRoute';
// styles
import styles from '../styles/Authen.module.css';

const Login = () => {
  const { login } = useAuth();
  const [emailVal, setEmailVal] = useState(null);
  const [passwordVal, setPasswordVal] = useState(null);

  const [inputError, setInputError] = useState(null);
  const router = useRouter();

  const onChangeValue = (e, type) => {
    switch (type) {
      case 'email':
        setEmailVal(e.target.value);
        break;
      case 'password':
        setPasswordVal(e.target.value);
        break;
    }
  };

  const onClickRegister = () => {
    router.push('/register');
  };

  const onSubmit = async () => {
    const postData = {
      username: emailVal,
      password: passwordVal,
    };

    const loginData = await login(postData);
    if (loginData === undefined) {
      setInputError('ข้อมูลไม่ถูกต้องกรุณาลองใหม่อีกครั้ง');
    } else {
      localStorage.setItem('token', loginData.token);
      router.push('/profile');
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Front End</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Login</h1>
        <input
          className={styles.input}
          onChange={(e) => onChangeValue(e, 'email')}
          placeholder="Email"
        />
        <input
          className={styles.input}
          onChange={(e) => onChangeValue(e, 'password')}
          placeholder="Password"
          type="password"
        />
        <button className={styles.button} onClick={onSubmit}>
          Login
        </button>
        {inputError && <p className={styles.error}>{inputError}</p>}
        <p className={styles.register} onClick={onClickRegister}>
          Register
        </p>
      </main>
    </div>
  );
};

export default withPublic(Login);
