/* eslint-disable react-hooks/exhaustive-deps */
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
// hooks
import { useAuth } from '../hooks/useAuth';
import { withProtected } from '../hooks/useRoute';
// styles
import styles from '../styles/Authen.module.css';

const Profile = () => {
  const { setUserData, updateUserData, userData } = useAuth();
  const [nameVal, setNameVal] = useState(null);

  const [inputError, setInputError] = useState(null);
  const router = useRouter();

  const onChangeValue = (e) => {
    setNameVal(e.target.value);
  };

  const onLogout = () => {
    setUserData(null);
    localStorage.removeItem('token');
    router.push('/');
  };

  const onUpdate = async () => {
    const updateData = {
      id: userData.id,
      name: nameVal,
    };
    const data = await updateUserData(updateData);
    if (data.success) {
      router.reload();
    } else {
      setInputError('ไม่สามารถแก้ไขข้อมูลได้');
    }
  };

  useEffect(() => {
    setNameVal(userData.name);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Front End</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Profile</h1>
        <input
          className={styles.input}
          onChange={onChangeValue}
          placeholder="Name"
          value={nameVal !== null ? nameVal : ''}
        />
        <div>
          <button className={styles.button} onClick={onUpdate}>
            Update
          </button>
          <button className={styles.button} onClick={onLogout}>
            Logout
          </button>
        </div>
        {inputError && <p className={styles.error}>{inputError}</p>}
      </main>
    </div>
  );
};

export default withProtected(Profile);
